// Regenerates ORAL_REVIEW.pdf from the oral bank so the printable review can
// never drift from the data. Formatting and export only; the content is the
// same as ORAL_REVIEW.md. Run: npm run oral-pdf
import { createWriteStream } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import PDFDocument from 'pdfkit'
import {
  oralBank,
  isComplete,
  ORAL_CATEGORIES,
  CATEGORY_LABELS,
  FREQ_LABELS,
  FREQ_DETAIL,
} from '../src/data/oralBank.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outPath = join(root, 'ORAL_REVIEW.pdf')

// Same hard failures as oral-review.mjs: nothing half-written slips through.
for (const q of oralBank) {
  const hasAny = q.conceptExplanation || q.spokenVersion || q.mcq || q.flashcardAnswer
  if (hasAny && !isComplete(q)) {
    throw new Error(`Half-complete entry ${q.id}: write all four content fields or none.`)
  }
  const texts = [q.question, q.conceptExplanation, q.flashcardAnswer, ...(q.spokenVersion ?? []), ...(q.mcq?.options ?? [])]
  for (const t of texts) {
    if (typeof t === 'string' && t.includes('—')) throw new Error(`Em-dash found on ${q.id}`)
  }
}

const complete = oralBank.filter(isComplete).length

// A4 in points, with margins comfortable for print and phone reading.
const MARGIN = 54
const doc = new PDFDocument({ size: 'A4', margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN }, bufferPages: true })
doc.pipe(createWriteStream(outPath))

const WIDTH = doc.page.width - MARGIN * 2
const BOTTOM = doc.page.height - MARGIN

const INK = '#33261b'
const MUT = '#63513f'
const ACCENT = '#a84e27'
const GOOD = '#1b7a44'

function remaining() {
  return BOTTOM - doc.y
}

function measure(font, size, text, opts = {}) {
  doc.font(font).fontSize(size)
  return doc.heightOfString(text, { width: WIDTH, ...opts })
}

// ---------- cover page ----------
const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

doc.moveDown(6)
doc.font('Times-Bold').fontSize(28).fillColor(INK).text('Oral Interview Bank Review', { align: 'center' })
doc.moveDown(0.5)
doc.font('Times-Roman').fontSize(13).fillColor(MUT).text(`${oralBank.length} technical questions, ${complete} with written answers`, { align: 'center' })
doc.moveDown(0.2)
doc.font('Times-Roman').fontSize(13).fillColor(MUT).text(`Generated ${today}`, { align: 'center' })
doc.moveDown(3)
doc.font('Times-Bold').fontSize(12).fillColor(INK).text('Important', { align: 'left' })
doc.moveDown(0.3)
doc.font('Times-Roman').fontSize(11.5).fillColor(INK).text(
  'The answers in this document are unverified aviation theory written for study purposes. Some may be wrong or imprecise. Every answer must be checked by a qualified captain before it is trusted. Please mark anything incorrect, imprecise, or oddly phrased.',
  { lineGap: 3 }
)
doc.moveDown(0.8)
doc.font('Times-Roman').fontSize(11.5).fillColor(INK).text(
  'To the reviewer: each question has a number. Please note the question number next to anything that needs correction, with a short note of what is wrong.',
  { lineGap: 3 }
)
doc.moveDown(2)
doc.font('Times-Italic').fontSize(10).fillColor(MUT).text(
  'Questions are grouped by how often they came up across five interview question sets, most frequent first. Regenerated from the question bank with npm run oral-pdf; do not edit this file by hand.',
  { lineGap: 3 }
)

// ---------- question sections, one keep-together unit at a time ----------

// Renders one section (an array of draw steps with a known total height),
// breaking to a new page first if it does not fit in the space remaining.
function keepTogether(height, draw) {
  if (height > remaining()) doc.addPage()
  draw()
}

function drawTierHeading(freq, tier) {
  doc.addPage()
  doc.font('Helvetica-Bold').fontSize(10).fillColor(ACCENT).text(FREQ_DETAIL[freq].toUpperCase(), { characterSpacing: 1 })
  doc.moveDown(0.15)
  doc.font('Times-Bold').fontSize(20).fillColor(INK).text(`Frequency ${freq}: ${FREQ_LABELS[freq]}`)
  doc.moveDown(0.1)
  doc.font('Times-Roman').fontSize(11).fillColor(MUT).text(`${tier.length} questions in this tier.`)
  doc.moveDown(1)
}

let n = 0
for (const freq of [5, 4, 3, 2, 1]) {
  const tier = oralBank.filter((q) => q.frequency === freq)
  if (!tier.length) continue
  drawTierHeading(freq, tier)

  for (const category of ORAL_CATEGORIES) {
    for (const q of tier.filter((x) => x.category === category)) {
      n += 1
      const headerText = `${n}. ${q.question}`
      const tagText = `${CATEGORY_LABELS[q.category].toUpperCase()}   ${q.id}`

      const sections = []

      // Header: question + tag line, always kept with the concept explanation.
      const headerH =
        measure('Times-Bold', 12.5, headerText, { lineGap: 2 }) +
        measure('Helvetica', 7.5, tagText) +
        10
      const drawHeader = () => {
        doc.font('Times-Bold').fontSize(12.5).fillColor(INK).text(headerText, { lineGap: 2 })
        doc.moveDown(0.15)
        doc.font('Helvetica').fontSize(7.5).fillColor(ACCENT).text(tagText, { characterSpacing: 0.5 })
        doc.moveDown(0.35)
      }

      if (!isComplete(q)) {
        sections.push({
          h: headerH + measure('Times-Italic', 11, 'PENDING: answer not yet written.') + 14,
          draw: () => {
            drawHeader()
            doc.font('Times-Italic').fontSize(11).fillColor(MUT).text('PENDING: answer not yet written.')
            doc.moveDown(1.2)
          },
        })
      } else {
        sections.push({
          h: headerH + measure('Times-Roman', 10.5, q.conceptExplanation, { lineGap: 2.5 }) + 8,
          draw: () => {
            drawHeader()
            doc.font('Times-Roman').fontSize(10.5).fillColor(INK).text(q.conceptExplanation, { lineGap: 2.5 })
            doc.moveDown(0.5)
          },
        })

        const bullets = q.spokenVersion.map((b) => `•  ${b}`).join('\n')
        sections.push({
          h: measure('Helvetica-Bold', 8, 'SPOKEN ANSWER SKELETON') + measure('Times-Roman', 10.5, bullets, { lineGap: 2.5 }) + 14,
          draw: () => {
            doc.font('Helvetica-Bold').fontSize(8).fillColor(ACCENT).text('SPOKEN ANSWER SKELETON', { characterSpacing: 0.5 })
            doc.moveDown(0.25)
            doc.font('Times-Roman').fontSize(10.5).fillColor(INK).text(bullets, { lineGap: 2.5, indent: 6 })
            doc.moveDown(0.5)
          },
        })

        const mcqH =
          measure('Helvetica-Bold', 8, 'MULTIPLE CHOICE') +
          q.mcq.options.reduce((s, opt, i) => {
            const line = i === q.mcq.correctIndex ? `${opt}   <- marked answer` : opt
            const font = i === q.mcq.correctIndex ? 'Times-Bold' : 'Times-Roman'
            return s + measure(font, 10.5, `•  ${line}`, { lineGap: 2.5 })
          }, 0) +
          14
        sections.push({
          h: mcqH,
          draw: () => {
            doc.font('Helvetica-Bold').fontSize(8).fillColor(ACCENT).text('MULTIPLE CHOICE', { characterSpacing: 0.5 })
            doc.moveDown(0.25)
            q.mcq.options.forEach((opt, i) => {
              if (i === q.mcq.correctIndex) {
                doc.font('Times-Bold').fontSize(10.5).fillColor(GOOD).text(`•  ${opt}   <- marked answer`, { lineGap: 2.5, indent: 6 })
              } else {
                doc.font('Times-Roman').fontSize(10.5).fillColor(INK).text(`•  ${opt}`, { lineGap: 2.5, indent: 6 })
              }
            })
            doc.moveDown(0.5)
          },
        })

        sections.push({
          h: measure('Helvetica-Bold', 8, 'FLASHCARD ANSWER') + measure('Times-Italic', 10.5, q.flashcardAnswer, { lineGap: 2.5 }) + 18,
          draw: () => {
            doc.font('Helvetica-Bold').fontSize(8).fillColor(ACCENT).text('FLASHCARD ANSWER', { characterSpacing: 0.5 })
            doc.moveDown(0.25)
            doc.font('Times-Italic').fontSize(10.5).fillColor(MUT).text(q.flashcardAnswer, { lineGap: 2.5 })
            doc.moveDown(1.4)
          },
        })
      }

      // Keep the whole question on one page when it fits anywhere; otherwise
      // fall back to keeping each section intact so no paragraph ever splits.
      const total = sections.reduce((s, x) => s + x.h, 0)
      const usable = BOTTOM - MARGIN
      if (total <= usable) {
        keepTogether(total, () => sections.forEach((s) => s.draw()))
      } else {
        for (const s of sections) keepTogether(s.h, s.draw)
      }
    }
  }
}

// ---------- footers ----------
const range = doc.bufferedPageRange()
for (let i = range.start; i < range.start + range.count; i++) {
  doc.switchToPage(i)
  if (i === 0) continue // no footer on the cover
  // Zero the bottom margin while stamping the footer: writing inside the
  // margin area would otherwise make pdfkit auto-append pages.
  const prevBottom = doc.page.margins.bottom
  doc.page.margins.bottom = 0
  doc.font('Helvetica').fontSize(8).fillColor(MUT)
  doc.text('Oral Interview Bank Review', MARGIN, doc.page.height - 36, { width: WIDTH / 2, lineBreak: false })
  doc.text(`Page ${i} of ${range.count - 1}`, MARGIN + WIDTH / 2, doc.page.height - 36, { width: WIDTH / 2, align: 'right', lineBreak: false })
  doc.page.margins.bottom = prevBottom
}

doc.end()
console.log(`ORAL_REVIEW.pdf written: ${oralBank.length} questions (${complete} with answers), ${range.count} pages.`)
